# Generated by Django 5.0 on 2024-11-19 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_TallerMecanico', '0005_cliente_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='informe',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='registro',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='App_TallerMecanico.registro'),
        ),
        migrations.AlterField(
            model_name='informe',
            name='trabajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informes', to='App_TallerMecanico.trabajo'),
        ),
        migrations.AlterField(
            model_name='mecanico',
            name='registro',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mecanico', to='App_TallerMecanico.registro'),
        ),
    ]
