# Generated by Django 5.0 on 2024-12-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_TallerMecanico', '0007_cita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='servicio',
            field=models.CharField(choices=[('mantenimiento', 'Mantenimiento'), ('reparacion', 'Reparación'), ('inspeccion', 'Inspección')], max_length=20),
        ),
    ]
