# Generated by Django 5.0 on 2024-12-17 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_TallerMecanico', '0011_administrador_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='mecanico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos', to='App_TallerMecanico.mecanico'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='App_TallerMecanico.cliente'),
        ),
    ]
