# Generated by Django 5.0 on 2024-12-17 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_TallerMecanico', '0012_vehiculo_mecanico_alter_vehiculo_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='informe',
            name='cita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informes', to='App_TallerMecanico.cita'),
        ),
        migrations.AddField(
            model_name='informe',
            name='cliente',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='informes', to='App_TallerMecanico.cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='informe',
            name='mecanico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informes', to='App_TallerMecanico.mecanico'),
        ),
    ]
