# Generated by Django 5.0 on 2024-12-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_TallerMecanico', '0016_remove_informe_cita_alter_informe_mecanico'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='anio',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cita',
            name='marca',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cita',
            name='modelo',
            field=models.CharField(default=5, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cita',
            name='patente',
            field=models.CharField(default=8, max_length=10),
            preserve_default=False,
        ),
    ]
